#!/bin/sh

cd website
yarn install
yarn run write-translations

wget https://downloads.crowdin.com/cli/v2/crowdin-cli.zip

unzip crowdin-cli.zip -d crowdin-cli

cp crowdin-cli/**/crowdin-cli.jar .

java -jar crowdin-cli.jar --config ../crowdin.yaml upload sources --auto-update -b master
java -jar crowdin-cli.jar --config ../crowdin.yaml download -b master

yarn run build
